# Generated by Django 5.0.8 on 2024-12-05 04:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_genero_libros_remove_libro_prestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_membresia', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_membresia', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='reservado',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='reservado_por',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='estado_membresia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numero_membresia',
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='dias_prestamo',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Lector', 'Lector'), ('Empleado', 'Empleado')], default='Lector', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
